### ISSUE TITLE
ImportError: cannot import name lzma on python2

### ISSUE THREAD

**Issue by dafuki** [JonathonReinhart/staticx#127]
I'm using debian 10, and python2.7

Trying to compile a pyinstaller compiled file i get this error
`Traceback` (most recent call last):
  File "/home/username/.local/bin/staticx", line 6, in <module>
    from staticx.__main__ import main
  File "/home/username/.local/lib/python2.7/site-packages/staticx/__main__.py", line 6, in <module>
    from .api import generate
  File "/home/username/.local/lib/python2.7/site-packages/staticx/api.py", line 15, in <module>
    from .archive import SxArchive
  File "/home/username/.local/lib/python2.7/site-packages/staticx/archive.py", line 11, in <module>
    from backports import lzma
ImportError: cannot import name lzma`

I do have backports installed, and apparently also lzma.
Been circling the web trying to figure out what I have been doing wrong, unsuccessfully.
Tried it on another Debian 10 VM, same results.
Installed Ubuntu 18 LTS and got it working.

**Comment by JonathonReinhart** [comment]
Hi @dafuki. I'm not really interested in fixing Python 2 bugs anymore. In fact I'm close to removing support for Python 2 altogether (#115). Is there any reason you care to run staticx under Python 2 instead of Python 3? Debian 8 has Python 3.4 and CentOS 7 has Python 3.6.

Even if you are using staticx to bundle up a PyInstalled Python 2 application, you could still use StaticX from Python 3.
