### ISSUE TITLE
Does staticx affect performance and/or stability in any way?

### ISSUE THREAD

**Issue by TimotheeJeannin** [JonathonReinhart/staticx#160]
I have created a static executable of libvips with staticx. I launched our complete test suite and the executable seem to work very well in a replica of our production environment. Should I have any reason to worry about the performance or the stability of the executable compared to the original one?

**Comment by JonathonReinhart** [comment]
> Should I have any reason to worry about the performance or the stability of the executable compared to the original one?

 Hi @TimotheeJeannin, great question. In general, the answer is: "No, you should not worry." A staticx-produced executable should behave the same as the original. But let's dig in.

### Performance

#### Startup
The place you might see a performance impact is the increased startup time of your executable. This is because the resulting executable is essentially a self-extracting `.tar.xz` archive. Depending on the size of your executable, this could be significant.

If the startup time is problematic, there are a few things you can do:
- Consider running staticx with `--no-compress`
  - This will omit the XZ (LZMA) compression and store the tar archive uncompressed. This of course comes at the cost of a larger archive and output file.
  - This might be important if the decompression is slower than I/O
- On the target system, ensure `/tmp` or `$TMPDIR` are on `tmpfs`
  - This will avoid writing temporary files to disk

You did get me thinking, and I opened #161 and #162.

#### Runtime
The runtime performance of the executable should be identical. Other than effectively changing the dynamic loader uses to find dependent shared libraries, Staticx doesn't change the way the program runs.

### Stability
Most of the problems with Staticx-produced executables look like "my program runs fine on my machine but not another machine". In the past, I think a lot of these were caused by #129, which has hopefully been resolved.

In general, if your program successfully starts on the target machine (meaning it was successfully loaded by the dynamic loader and `main()` was called), then you should be good to go.

The exception to this is if your program (or its libraries) uses `dlopen()` to dynamically load libraries at runtime. This is covered in the README:
> However, libraries loaded by an application at runtime via `dlopen()` cannot currently be detected.

---

Hope this helps. Let me know how it goes!

**Comment by TimotheeJeannin** [comment]
Hi @JonathonReinhart,

Thank you for this detailed answer. Maybe it could be nice to mention the --no-compress parameter in the readme ? 

Amazing work ! Have a great day ! :)
