### ISSUE TITLE
This project can be built on debian, not on CentOS, for reproducibility reason.

### ISSUE THREAD

**Issue by sansna** [JonathonReinhart/staticx#202]
I think the [README.md](https://github.com/JonathonReinhart/staticx/blob/master/README.md) should point it out.

**Comment by JonathonReinhart** [comment]
Sorry, I don't understand what you're trying to say.  What exactly isn't working on CentOS and what is the "reproducibility reason"?

If there is some specific reason staticx can't support CentOS, then I will gladly update the readme to explain it. But you haven't indicated what that reason is. And I would rather fix the problem anyway.
